#161967024 Modify Articles get endpoint for to counter Pagination
andela/ah-jumanji pull request #22
Opened 2018-12-12 08:19 UTC by fabischolasi

#### What does this PR do?
This PR  enables pagination for the articles. This means that instead of the articles being returned all of them in one page, they are returned in chunks till they are all exhausted from the DB.

#### Description of Task to be completed?

#### How should this be manually tested?
```
1.  Clone this repo <git clone https://github.com/andela/ah-jumanji.git> via the terminal, cd into the directory and activate the virtual environment.
2. Run pip install -r requirements.txt to install all the dependencies
3. 
```
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

#### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] At least 2 people have reviewed my PR
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] My PR has one commit.

2018-12-12 20:05 UTC, GransonO commented
I noticed Hound is not appearing as part of your tests!

2018-12-12 20:09 UTC, fabischolasi commented
Let me check why its not appearing

2018-12-13 05:52 UTC, ghost reviewed
This can be merged. COnsider looking into why there's a `coverage` drop though.

2018-12-13 07:09 UTC, fabischolasi commented
Alright

2018-12-13 08:15 UTC, mashafrancis commented
Awesome work. I have tested the functionality and it works well. Consider updating the ReadMe as well for full instructions while testing. Some instructions missed from No 7 after posting an article, like getting the pagination link to work on postman.

2018-12-13 08:52 UTC, fabischolasi commented
Done

2018-12-13 12:02 UTC, EmmanuelBeja approved these changes

2018-12-13 13:01 UTC, ghost requested changes
Please refactor the `tests` to be more `accurate and descriptive` by checking for specific parameters from the `response`.

2018-12-13 13:09 UTC, mirr254 requested changes

2018-12-13 13:09 UTC, mirr254 commented on authors/apps/articles/tests/endpoints/test_get.py
> +        self.assertIn(b"1", response.content)  # article id
There are 2 similar tests achieving different results. I think it would be better to have descriptive test names.

2018-12-13 13:09 UTC, mirr254 commented on authors/apps/articles/tests/endpoints/test_get.py
> +        self.assertIn(b"life,love,death", response.content)  # taglist
Same applies to all other tests ☝️

2018-12-13 13:58 UTC, gitau-kinuthia requested changes
Please add exception handling for assertion error handling in the class view. The exception raised should be caught and a custom message returned

2018-12-13 16:20 UTC, GransonO reviewed
Complete the raised issues before the merge can be facilitated.

2018-12-14 09:19 UTC, mirr254 approved these changes

2018-12-14 09:23 UTC, ghost approved these changes

2018-12-17 06:44 UTC, merged